server:
  port: 30002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
spring:
  application:
    name: feign
  zipkin:
    base-url: http://localhost:9411/
feign:
  hystrix:
    enable: true